apiVersion: apps/v1
kind: Deployment
metadata:
  name: pregod-hub
  namespace: pregod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pregod-hub
      tier: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pregod-hub
        tier: api
    spec:
      containers:
        - image: IMAGE
          imagePullPolicy: Always
          name: app
          command:
            - ./hub
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "250m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config
              mountPath: "/rss3-pregod/config"
              readOnly: true
            - name: mongo-ca
              mountPath: "/rds-combined-ca-bundle.pem"
              subPath: rds-combined-ca-bundle.pem
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            secretName: pregod-hub
        - name: mongo-ca
          configMap:
            name: rds-combined-ca-bundle.pem
            items:
              - key: rds-combined-ca-bundle.pem
                path: rds-combined-ca-bundle.pem
